import type { Metadata, Viewport } from 'next'
import { headers } from 'next/headers'
import './globals.css'
import { ThemeProvider } from '@/lib/theme'
import { I18nProvider } from '@/lib/i18n'
import { PreloaderWrapper } from '@/components/preloader-wrapper'
import { ToasterProvider } from '@/components/toaster-provider'
import MaintenanceOverlay from '@/components/maintenance-overlay'
import { ServiceWorkerRegister } from '@/components/sw-register'

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
  title: 'Hostel Food Review System',
  description: 'Rate your hostel meals and help the management improve food quality. Instant feedback, real-time analytics, and daily menu updates.',
  applicationName: 'Hostel Food Review',
  keywords: ['hostel', 'food review', 'meal rating', 'campus food', 'student feedback'],
  authors: [{ name: 'Hostel Management' }],
  openGraph: {
    type: 'website',
    title: 'Hostel Food Review System',
    description: 'Rate your hostel meals and help the management improve food quality.',
    siteName: 'Hostel Food Review',
    locale: 'en_IN',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Hostel Food Review System',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Hostel Food Review System',
    description: 'Rate your hostel meals and help the management improve food quality.',
    images: ['/og-image.png'],
  },
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Food Review',
  },
  formatDetection: {
    telephone: false,
  },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: [{ media: '(prefers-color-scheme: dark)', color: '#000000' }, { media: '(prefers-color-scheme: light)', color: '#ffffff' }],
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Read the CSP nonce generated by middleware for inline scripts
  const headersList = await headers()
  const nonce = headersList.get('x-nonce') || ''

  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <script
          nonce={nonce}
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='light'){document.documentElement.classList.remove('dark')}else{document.documentElement.classList.add('dark')}}catch(e){}})();`,
          }}
        />
      </head>
      <body className="min-h-screen bg-background text-foreground font-sans antialiased transition-colors duration-200">
        <ThemeProvider>
          <I18nProvider>
            <PreloaderWrapper />
            <MaintenanceOverlay />
            <ServiceWorkerRegister />
            {children}
            <ToasterProvider />
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
